import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./ui/globals.css";
import AuthProvider from "@/components/AuthProvider";


const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sahityotsav workspace App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
      
        {children}
        </body>
        </AuthProvider>
    </html>
  );
}
